/**
 * Append-only barrel (05-EXECUTION-PLAN.md §3) — each task adds its own `export * from
 * './domain-file'` line and touches nothing else, so parallel tasks never collide here.
 * One Zod-schema file per domain (campaign.schema.ts, rule.schema.ts, ...), never a single
 * shared file multiple tasks edit at once.
 *
 * T-001 (this task) intentionally adds no domain exports — it only proves the package
 * builds, type-checks and is importable from both workspaces. The first domain schema
 * (role/permission enums, most likely) is added by whichever task first needs it.
 */
export const SHARED_PACKAGE_NAME = '@reward-portal/shared';

// T-015 — the `/me` wire contract: the `GET /me/bootstrap` payload that drives the whole UI, the
// `GET /me` profile, and the three-field `PATCH /me` body. First domain schema in the package.
export * from './bootstrap.schema';

// T-045 — the `GET /audit/trace/:correlationId` wire contract (08-OBSERVABILITY.md §6).
export * from './trace.schema';

// T-030 — the `/countries` wire contract (country onboarding + Country Admin onboarding).
export * from './country.schema';

// T-031 — the `/rules` wire contract (rule authoring + country assignment). Exported under its
// own name where a symbol would otherwise collide with `country.schema`'s `listMetaSchema`.
export {
  RULE_PARAMETER_TYPES,
  RULE_STATUSES,
  assignRuleCountryRequestSchema,
  createRuleCategoryRequestSchema,
  createRuleRequestSchema,
  createRuleSubCategoryRequestSchema,
  ruleCategoryEnvelopeSchema,
  ruleCategoryListEnvelopeSchema,
  ruleCategorySchema,
  ruleCountryAssignmentEnvelopeSchema,
  ruleCountryAssignmentListEnvelopeSchema,
  ruleCountryAssignmentSchema,
  ruleEnvelopeSchema,
  ruleListEnvelopeSchema,
  ruleOperatorListEnvelopeSchema,
  ruleOperatorSchema,
  // T-114 — resolver-driven parameter-field role: response-only, never part of the write shape
  // (`ruleParameterFieldSchema`/`ruleParametersSchema`, unchanged, exported above).
  RULE_FIELD_ROLES,
  ruleFieldRoleSchema,
  // T-122 — an optional value source on a `select` parameter field: its options come from a
  // registered context/API lookup provider instead of a hand-typed `options` array. Part of the
  // **write** shape (unlike `role` above), so `createRuleRequestSchema`/`updateRuleRequestSchema`
  // both carry it.
  RULE_FIELD_VALUE_SOURCE_KINDS,
  ruleFieldValueSourceSchema,
  ruleParameterFieldSchema,
  ruleParameterFieldWithRoleSchema,
  ruleParameterTypeSchema,
  ruleParametersEnvelopeSchema,
  ruleParametersSchema,
  ruleParametersWithRoleSchema,
  ruleResolverListEnvelopeSchema,
  ruleResolverSchema,
  ruleSchema,
  ruleStatusSchema,
  ruleSubCategoryEnvelopeSchema,
  ruleSubCategoryListEnvelopeSchema,
  ruleSubCategorySchema,
  updateRuleCategoryRequestSchema,
  updateRuleRequestSchema,
  updateRuleSubCategoryRequestSchema,
  type AssignRuleCountryRequest,
  type CreateRuleCategoryRequest,
  type CreateRuleRequest,
  type CreateRuleSubCategoryRequest,
  type Rule,
  type RuleCategory,
  type RuleCountryAssignment,
  type RuleFieldRole,
  type RuleFieldValueSource,
  type RuleOperator,
  type RuleParameterField,
  type RuleParameterFieldWithRole,
  type RuleParameterType,
  type RuleParameters,
  type RuleParametersWithRole,
  type RuleResolver,
  type RuleStatus,
  type RuleSubCategory,
  type UpdateRuleCategoryRequest,
  type UpdateRuleRequest,
  type UpdateRuleSubCategoryRequest,
} from './rule.schema';

// T-032 — the `/rewards` wire contract (reward authoring + country assignment). The reward
// equivalent of T-031's rule.schema.ts export block above, exported under its own name for the
// same collision reasons (`listMetaSchema` is module-private in both files).
export {
  REWARD_CONNECTOR_CONFIG_MAX_KEYS,
  REWARD_CONNECTOR_TYPES,
  REWARD_DELIVERY_MODES,
  REWARD_POLICY_CAP_FREQUENCY_UNITS,
  REWARD_POLICY_CAP_STATUSES,
  REWARD_POLICY_CAP_TYPES,
  REWARD_POLICY_STATUSES,
  REWARD_STATUSES,
  assignRewardCountryRequestSchema,
  createRewardPolicyCapRequestSchema,
  createRewardPolicyRequestSchema,
  createRewardRequestSchema,
  maskedRewardConnectorConfigSchema,
  rewardConnectorConfigSchema,
  rewardConnectorTypeSchema,
  rewardCountryAssignmentEnvelopeSchema,
  rewardCountryAssignmentListEnvelopeSchema,
  rewardCountryAssignmentSchema,
  rewardDeliveryModeSchema,
  rewardEnvelopeSchema,
  rewardListEnvelopeSchema,
  rewardListItemSchema,
  rewardPolicyCapEnvelopeSchema,
  rewardPolicyCapFrequencyUnitSchema,
  rewardPolicyCapListEnvelopeSchema,
  rewardPolicyCapSchema,
  rewardPolicyCapStatusSchema,
  rewardPolicyCapTypeSchema,
  rewardPolicyEnvelopeSchema,
  rewardPolicyListEnvelopeSchema,
  rewardPolicySchema,
  rewardPolicyStatusSchema,
  rewardSchema,
  rewardStatusSchema,
  rewardTypeSchema,
  updateRewardPolicyCapRequestSchema,
  updateRewardPolicyRequestSchema,
  updateRewardRequestSchema,
  // T-116 — reward categories/sub-categories (mirrors `rule.schema.ts`'s own category exports
  // above). Added by T-117: `reward.schema.ts` itself already had these (T-116), but this
  // barrel's own export list — the thing that actually makes them importable from
  // `@reward-portal/shared` — never did, so nothing outside `reward.schema.ts` could reach them
  // until now.
  createRewardCategoryRequestSchema,
  createRewardSubCategoryRequestSchema,
  rewardCategoryEnvelopeSchema,
  rewardCategoryListEnvelopeSchema,
  rewardCategorySchema,
  rewardSubCategoryEnvelopeSchema,
  rewardSubCategoryListEnvelopeSchema,
  rewardSubCategorySchema,
  updateRewardCategoryRequestSchema,
  updateRewardSubCategoryRequestSchema,
  // T-119 — reward version Kind + per-kind value config (13-REWARD-MASTER-VALUE-SOURCES.md §5).
  PROMO_CODE_API_PROVIDERS,
  PROMO_CODE_BIND_LEVELS,
  REWARD_KINDS,
  checkRewardVersionValue,
  createRewardVersionRequestSchema,
  fixedAmountValueConfigSchema,
  isRewardVersionValue,
  percentageValueConfigSchema,
  physicalValueConfigSchema,
  pointsValueConfigSchema,
  promoCodeApiProviderSchema,
  promoCodeBindLevelSchema,
  promoCodeValueConfigSchema,
  rewardKindSchema,
  rewardValueConfigSchema,
  rewardVersionValueRequestFields,
  rewardVersionValueResponseFields,
  rewardVersionValueSchema,
  type CreateRewardVersionRequest,
  type PromoCodeBindLevel,
  type RewardKind,
  type RewardVersionValue,
  type AssignRewardCountryRequest,
  type CreateRewardCategoryRequest,
  type CreateRewardPolicyCapRequest,
  type CreateRewardPolicyRequest,
  type CreateRewardRequest,
  type CreateRewardSubCategoryRequest,
  type MaskedRewardConnectorConfig,
  type Reward,
  type RewardCategory,
  type RewardConnectorConfig,
  type RewardConnectorType,
  type RewardCountryAssignment,
  type RewardDeliveryMode,
  type RewardListItem,
  type RewardPolicy,
  type RewardPolicyCap,
  type RewardStatus,
  type RewardSubCategory,
  type UpdateRewardCategoryRequest,
  type UpdateRewardPolicyCapRequest,
  type UpdateRewardPolicyRequest,
  type UpdateRewardRequest,
  type UpdateRewardSubCategoryRequest,
} from './reward.schema';

// T-033 — the `/admin/access-control` wire contract (Super Admin nav/permissions/widgets admin).
export {
  entityCatalogueEntrySchema,
  entityCatalogueListEnvelopeSchema,
  navConfigEnvelopeSchema,
  navConfigItemRequestSchema,
  navConfigItemSchema,
  navConfigResponseSchema,
  permissionsEnvelopeSchema,
  permissionsResponseSchema,
  previewEnvelopeSchema,
  previewRequestSchema,
  previewResponseSchema,
  putNavConfigRequestSchema,
  putPermissionsRequestSchema,
  putWidgetConfigRequestSchema,
  reorderItemSchema,
  reorderRequestSchema,
  roleSummaryListEnvelopeSchema,
  roleSummarySchema,
  widgetConfigEnvelopeSchema,
  widgetConfigItemRequestSchema,
  widgetConfigItemSchema,
  widgetConfigResponseSchema,
  type EntityCatalogueEntry,
  type NavConfigItem,
  type NavConfigItemRequest,
  type NavConfigResponse,
  type PermissionsResponse,
  type PreviewRequest,
  type PreviewResponse,
  type PutNavConfigRequest,
  type PutPermissionsRequest,
  type PutWidgetConfigRequest,
  type ReorderRequest,
  type RoleSummary,
  type WidgetConfigItem,
  type WidgetConfigItemRequest,
  type WidgetConfigResponse,
} from './access-control.schema';

// T-034 — the `/tenants` wire contract (tenant onboarding + Tenant Admin onboarding + budget
// ceilings). Exported under its own name where a symbol would otherwise collide with
// `country.schema`'s `listMetaSchema` (`tenantListMetaSchema` here), the same reasoning T-031's
// own export block gives.
export {
  TENANT_BUDGET_CEILING_UNIT_TYPES,
  TENANT_STATUSES,
  budgetCeilingListEnvelopeSchema,
  budgetCeilingSchema,
  createTenantAdminRequestSchema,
  createTenantEnvelopeSchema,
  createTenantRequestSchema,
  createTenantResponseSchema,
  tenantAdminCreatedEnvelopeSchema,
  tenantAdminCreatedSchema,
  tenantBudgetCeilingUnitTypeSchema,
  tenantEnvelopeSchema,
  tenantListEnvelopeSchema,
  tenantListMetaSchema,
  tenantSchema,
  tenantStatusSchema,
  tenantWithoutCeilingListEnvelopeSchema,
  tenantWithoutCeilingSchema,
  updateTenantRequestSchema,
  upsertBudgetCeilingRequestSchema,
  type BudgetCeiling,
  type CreateTenantAdminRequest,
  type CreateTenantRequest,
  type CreateTenantResponse,
  type Tenant,
  type TenantAdminCreated,
  type TenantBudgetCeilingUnitType,
  type TenantStatus,
  type TenantWithoutCeiling,
  type UpdateTenantRequest,
  type UpsertBudgetCeilingRequest,
} from './tenant.schema';

// T-035 — the `/users` wire contract (delegated user creation across the whole hierarchy).
export {
  USER_STATUSES,
  createUserRequestSchema,
  emptyRequestSchema,
  updateUserRequestSchema,
  userEnvelopeSchema,
  userListEnvelopeSchema,
  userListMetaSchema,
  userSchema,
  userStatusSchema,
  userWithTemporaryPasswordEnvelopeSchema,
  userWithTemporaryPasswordSchema,
  type CreateUserRequest,
  type UpdateUserRequest,
  type User,
  type UserStatus,
  type UserWithTemporaryPassword,
} from './user.schema';

// T-041 — the `/rules/:id/versions`, `/rewards/:id/versions`, `/blasts` and
// `/countries/:id/assigned-versions` wire contract (version lifecycle + blast distribution).
// Exported under its own name where a symbol would otherwise collide with `country.schema`'s
// `listMetaSchema` (`versionListMetaSchema` here), the same reasoning T-031/T-034's own export
// blocks give.
export {
  BLAST_SCOPES,
  BLAST_TARGET_STATUSES,
  VERSION_ASSIGNMENT_STATUSES,
  VERSION_ENTITY_TYPES,
  VERSION_STATUSES,
  assignedVersionListEnvelopeSchema,
  assignedVersionSchema,
  blastEnvelopeSchema,
  blastListEnvelopeSchema,
  blastPreviewCountryImpactSchema,
  blastPreviewEnvelopeSchema,
  blastPreviewResponseSchema,
  blastSchema,
  blastScopeSchema,
  blastTargetSchema,
  blastTargetStatusSchema,
  createBlastRequestSchema,
  createVersionRequestSchema,
  previewBlastRequestSchema,
  rewardVersionEnvelopeSchema,
  rewardVersionListEnvelopeSchema,
  rewardVersionSchema,
  ruleVersionEnvelopeSchema,
  ruleVersionListEnvelopeSchema,
  ruleVersionSchema,
  updateRewardVersionRequestSchema,
  updateRuleVersionRequestSchema,
  versionAssignmentStatusSchema,
  versionCountryAssignmentListEnvelopeSchema,
  versionCountryAssignmentSchema,
  versionDiffEnvelopeSchema,
  versionDiffSchema,
  versionEntityTypeSchema,
  versionStatusSchema,
  listMetaSchema as versionListMetaSchema,
  type AssignedVersion,
  type Blast,
  type BlastPreviewCountryImpact,
  type BlastPreviewResponse,
  type BlastScope,
  type BlastTarget,
  type BlastTargetStatus,
  type CreateBlastRequest,
  type CreateVersionRequest,
  type PreviewBlastRequest,
  type RewardVersion,
  type RuleVersion,
  type UpdateRewardVersionRequest,
  type UpdateRuleVersionRequest,
  type VersionAssignmentStatus,
  type VersionCountryAssignment,
  type VersionDiff,
  type VersionEntityType,
  type VersionStatus,
} from './version.schema';

// T-037 — the `/campaigns` wire contract (7-step maker wizard, journey builder, rule binding with
// dynamic values, three reward levels, budgets/limits, submission). Exported under its own name
// where a symbol would otherwise collide with `country.schema`'s `listMetaSchema` and with
// `rule.schema`/`version.schema`'s own `RuleParameters`-adjacent names — the same reasoning
// T-031/T-034/T-041/T-036's export blocks give.
export {
  CAMPAIGN_EFFECTIVE_STATUSES,
  CAMPAIGN_STATUSES,
  CAMPAIGN_WARNING_CODES,
  CAP_CLASSES,
  CAP_ON_BREACH,
  CAP_PERIOD_TYPES,
  CAP_SCOPE_LEVELS,
  CAP_UNIT_TYPES,
  REWARD_LEVELS,
  TRACKER_COMPLETION_LOGICS,
  attachRewardRequestSchema,
  bindComponentRuleRequestSchema,
  budgetCeilingStatusSchema,
  buildRuleValueSchema,
  campaignActivityOptionListEnvelopeSchema,
  campaignActivityOptionSchema,
  campaignAuditEntrySchema,
  campaignAuditListEnvelopeSchema,
  campaignCapInputSchema,
  campaignCapSchema,
  campaignCapsEnvelopeSchema,
  campaignCapsResponseSchema,
  campaignEffectiveStatusSchema,
  campaignEnvelopeSchema,
  campaignListEnvelopeSchema,
  campaignListMetaSchema,
  campaignMerchantListEnvelopeSchema,
  campaignMerchantSchema,
  campaignReviewEnvelopeSchema,
  campaignReviewSchema,
  campaignSchema,
  campaignStatusSchema,
  campaignWarningCodeSchema,
  campaignWarningSchema,
  capClassSchema,
  capOnBreachSchema,
  capPeriodTypeSchema,
  capScopeLevelSchema,
  capUnitTypeSchema,
  componentRuleSchema,
  componentSchema,
  createCampaignRequestSchema,
  createComponentRequestSchema,
  createTrackerRequestSchema,
  isBeforeTodayInItsOwnOffset,
  isoDateTimeSchema,
  journeyEnvelopeSchema,
  journeySchema,
  legacyMoneySchema,
  missingRequiredParameterKeys,
  moneySchema,
  putCampaignCapsRequestSchema,
  reorderComponentsRequestSchema,
  rewardAssignmentSchema,
  rewardLevelSchema,
  rewardOptionListEnvelopeSchema,
  rewardOptionSchema,
  ruleOptionListEnvelopeSchema,
  ruleOptionSchema,
  setCampaignMerchantsRequestSchema,
  structuralIssueSchema,
  submitCampaignEnvelopeSchema,
  submitCampaignRequestSchema,
  submitCampaignResponseSchema,
  timeOfDaySchema,
  trackerCompletionLogicSchema,
  trackerSchema,
  updateCampaignRequestSchema,
  updateComponentRequestSchema,
  updateComponentRuleValuesRequestSchema,
  updateTrackerRequestSchema,
  worstCasePayoutLineSchema,
  type AttachRewardRequest,
  type BindComponentRuleRequest,
  type BudgetCeilingStatus,
  type Campaign,
  type CampaignActivityOption,
  type CampaignAuditEntry,
  type CampaignCapInput,
  type CampaignCapRow,
  type CampaignCapsResponse,
  type CampaignEffectiveStatus,
  type CampaignMerchantLink,
  type CampaignReview,
  type CampaignStatus,
  type CampaignWarning,
  type CampaignWarningCode,
  type CapClass,
  type CapOnBreach,
  type CapPeriodType,
  type CapScopeLevel,
  type CapUnitType,
  type ComponentRule,
  type CreateCampaignRequest,
  type CreateComponentRequest,
  type CreateTrackerRequest,
  type Journey,
  type JourneyComponent,
  type JourneyTracker,
  type PutCampaignCapsRequest,
  type ReorderComponentsRequest,
  type RewardAssignment,
  type RewardLevel,
  type RewardOption,
  type RuleOption,
  type SetCampaignMerchantsRequest,
  type StructuralIssue,
  type SubmitCampaignResponse,
  type TrackerCompletionLogic,
  type UpdateCampaignRequest,
  type UpdateComponentRequest,
  type UpdateComponentRuleValuesRequest,
  type UpdateTrackerRequest,
  type WorstCasePayoutLine,
} from './campaign.schema';

// T-048 — the `/campaign-agent` wire contract (10-AI-CAMPAIGN-AGENT.md). It lives in
// `campaign.schema.ts` alongside T-037's block, not in a file of its own: the agent is a second way
// of authoring the same campaign, not a second domain — see that file's own T-048 header. Listed
// as its own export block here so the barrel still reads one-task-one-line (05-EXECUTION-PLAN §3).
export {
  AGENT_ARCHETYPES,
  AGENT_SESSION_STATES,
  agentArchetypeSchema,
  agentCreatedCampaignEnvelopeSchema,
  agentCreatedCampaignSchema,
  agentEventSchema,
  agentOptionSchema,
  agentOptionsSchema,
  agentPlanComponentSchema,
  agentPlanRewardSchema,
  agentPlanRuleSchema,
  agentPlanSchema,
  agentProgressSchema,
  agentSessionDetailEnvelopeSchema,
  agentSessionDetailSchema,
  agentSessionListEnvelopeSchema,
  agentSessionSchema,
  agentSessionStateSchema,
  agentTurnEnvelopeSchema,
  agentTurnSchema,
  confirmAgentPlanRequestSchema,
  sendAgentMessageRequestSchema,
  type AgentArchetype,
  type AgentCreatedCampaign,
  type AgentEvent,
  type AgentOption,
  type AgentOptions,
  type AgentPlan,
  type AgentPlanComponent,
  type AgentPlanReward,
  type AgentPlanRule,
  type AgentProgress,
  type AgentSession,
  type AgentSessionDetail,
  type AgentSessionState,
  type AgentTurn,
  type ConfirmAgentPlanRequest,
  type SendAgentMessageRequest,
} from './campaign.schema';

// T-036 — the `/merchants` wire contract (merchant directory, stores, activity links + commission
// rates). Exported under its own name where a symbol would otherwise collide with
// `country.schema`'s `listMetaSchema` (`merchantListMetaSchema` here), the same reasoning
// T-031/T-034/T-041's own export blocks give.
export {
  MERCHANT_STATUSES,
  createMerchantActivityRequestSchema,
  createMerchantRequestSchema,
  createMerchantStoreRequestSchema,
  merchantActiveCampaignListEnvelopeSchema,
  merchantActiveCampaignSchema,
  merchantActivityEnvelopeSchema,
  merchantActivityListEnvelopeSchema,
  merchantActivitySchema,
  merchantEnvelopeSchema,
  merchantListEnvelopeSchema,
  merchantListMetaSchema,
  merchantSchema,
  merchantStatusSchema,
  merchantStoreEnvelopeSchema,
  merchantStoreListEnvelopeSchema,
  merchantStoreSchema,
  updateMerchantRequestSchema,
  type CreateMerchantActivityRequest,
  type CreateMerchantRequest,
  type CreateMerchantStoreRequest,
  type Merchant,
  type MerchantActiveCampaign,
  type MerchantActivity,
  type MerchantStatus,
  type MerchantStore,
  type UpdateMerchantRequest,
} from './merchant.schema';

// T-038 — the `/approvals` wire contract (the checker's queue, the payload diff, and the three
// decisions). Exported under its own name where a symbol would otherwise collide with
// `country.schema`'s `listMetaSchema` — here it is already named `approvalListMetaSchema` in the
// source file, so the whole module is re-exported directly, the same as `campaign.schema`'s block
// does for its own uniquely-named members.
export {
  APPROVAL_ACTIONS,
  APPROVAL_COMMENT_MAX_LENGTH,
  APPROVAL_DIFF_PROBLEMS,
  APPROVAL_STATUSES,
  approvalActionSchema,
  approvalBudgetLineSchema,
  approvalDetailEnvelopeSchema,
  approvalDetailSchema,
  approvalDiffFieldSchema,
  approvalDiffProblemSchema,
  approvalDiffSchema,
  approvalEnvelopeSchema,
  approvalListEnvelopeSchema,
  approvalListMetaSchema,
  approvalRequestSchema,
  approvalStatusSchema,
  approvalSubjectSchema,
  approveApprovalRequestSchema,
  commentedDecisionRequestSchema,
  effectiveApprovalStatus,
  isApprovalExpired,
  rejectApprovalRequestSchema,
  returnApprovalRequestSchema,
  type ApprovalAction,
  type ApprovalBudgetLine,
  type ApprovalDetail,
  type ApprovalDiff,
  type ApprovalDiffField,
  type ApprovalDiffProblem,
  type ApprovalRequest,
  type ApprovalStatus,
  type ApprovalSubject,
  type ApproveApprovalRequest,
  type CommentedDecisionRequest,
} from './approval.schema';

// T-042 — the `/definition-requests` wire contract ("please build me a rule/reward",
// 06-VERSIONING.md §9). Exported under its own name where a symbol would otherwise collide with
// `country.schema`'s `listMetaSchema` (`definitionRequestListMetaSchema` here), the same
// reasoning T-031/T-034/T-036/T-041's own export blocks give.
export {
  DEFINITION_REQUEST_PRIORITIES,
  DEFINITION_REQUEST_REVIEW_TARGET_STATUSES,
  DEFINITION_REQUEST_STATUSES,
  DEFINITION_REQUEST_TYPES,
  createDefinitionRequestSchema,
  definitionRequestEnvelopeSchema,
  definitionRequestListEnvelopeSchema,
  definitionRequestPrioritySchema,
  definitionRequestReviewTargetStatusSchema,
  definitionRequestSchema,
  definitionRequestStatusSchema,
  definitionRequestTypeSchema,
  fulfilDefinitionRequestSchema,
  reviewDefinitionRequestSchema,
  updateDefinitionRequestSchema,
  listMetaSchema as definitionRequestListMetaSchema,
  type CreateDefinitionRequestRequest,
  type DefinitionRequest,
  type DefinitionRequestPriority,
  type DefinitionRequestStatus,
  type DefinitionRequestType,
  type FulfilDefinitionRequestRequest,
  type ReviewDefinitionRequestRequest,
  type UpdateDefinitionRequestRequest,
} from './definition-request.schema';

// T-039 — the `/merchant/campaigns`, `/merchant/campaigns/:id` and `/merchant/summary` wire
// contract (03-API-CONTRACT.md §13). No name collides with any other schema in this package, so
// (unlike `merchant.schema.ts`'s own block) nothing here needs an `as` rename.
export {
  MERCHANT_VISIBLE_CAMPAIGN_STATUSES,
  merchantCampaignDetailEnvelopeSchema,
  merchantCampaignDetailSchema,
  merchantCampaignListEnvelopeSchema,
  merchantCampaignListItemSchema,
  merchantCampaignPerformanceAvailableSchema,
  merchantCampaignPerformanceSchema,
  merchantCampaignPerformanceUnavailableSchema,
  merchantOwnActivitySchema,
  merchantSummaryEnvelopeSchema,
  merchantSummarySchema,
  merchantVisibleCampaignStatusSchema,
  type MerchantCampaignDetail,
  type MerchantCampaignListItem,
  type MerchantCampaignPerformance,
  type MerchantOwnActivity,
  type MerchantSummary,
  type MerchantVisibleCampaignStatus,
} from './merchant-portal.schema';

// T-128 — the `GET`/`PATCH /users/me/preferences` wire contract (self-service UI theme
// preference, 13-REWARD-MASTER-VALUE-SOURCES.md §6).
export {
  UI_THEMES,
  uiThemeSchema,
  updateUserPreferencesRequestSchema,
  userPreferencesEnvelopeSchema,
  userPreferencesSchema,
  type UiTheme,
  type UpdateUserPreferencesRequest,
  type UserPreferences,
} from './user-preferences.schema';

// T-126 — the `/tenants/:id/currencies` wire contract (13-REWARD-MASTER-VALUE-SOURCES.md §4).
// Exported under its own names — `TenantCurrency`/`TENANT_CURRENCY_STATUSES` would otherwise
// collide with `tenant.schema.ts`'s own `Tenant`/`TENANT_STATUSES`.
export {
  TENANT_CURRENCY_STATUSES,
  createTenantCurrencyRequestSchema,
  tenantCurrencyEnvelopeSchema,
  tenantCurrencyListEnvelopeSchema,
  tenantCurrencySchema,
  tenantCurrencyStatusSchema,
  updateTenantCurrencyRequestSchema,
  type CreateTenantCurrencyRequest,
  type TenantCurrency,
  type TenantCurrencyStatus,
  type UpdateTenantCurrencyRequest,
} from './tenant-currency.schema';

// T-121 — the two field value-source registries' wire contract
// (13-REWARD-MASTER-VALUE-SOURCES.md §3). Its own file rather than an addition to
// `rule.schema.ts`/`reward.schema.ts`: a value source is used by both, so hanging it off either
// would couple the two domain schemas together.
export * from './field-value-source.schema';
