/**
 * T-RAP-021. `activity_logs` — the fan-out ledger, the core table (`01-DATABASE.md` §3). This is
 * the one write path this module owns: a single, parameterised multi-row `INSERT ... ON CONFLICT
 * DO NOTHING RETURNING ...` statement, run inside a transaction the caller (`ActivityIngestionService`)
 * opens and passes in.
 *
 * **Why `ON CONFLICT DO NOTHING` and not a pre-check `SELECT`** (`05-PROCESSING-PIPELINE.md` §2,
 * task implementation note 4): a `SELECT`-then-`INSERT` pair is exactly the race `AGENT-PROTOCOL.md`
 * R2/TC-7 exist to rule out — two concurrent callers could both see "not found" and both attempt the
 * insert, one of them crashing on the unique-constraint violation the other caller's own in-flight
 * (uncommitted) insert doesn't yet make visible to a plain `SELECT`. `ON CONFLICT DO NOTHING` folds
 * the check and the write into one atomic statement Postgres itself serializes: whichever caller's
 * transaction commits first wins every contested row, the other's conflicting rows are silently
 * skipped (never a thrown unique-violation), and `RETURNING` tells each caller exactly which of
 * *its own* rows actually landed — the caller (not this repository) turns that into
 * `accepted`/`duplicate` (task implementation note 4: "no special-casing" needed here for the
 * partial-duplicate case either — a config-driven change in which components now match is handled
 * by the exact same statement, no different code path).
 *
 * One multi-row `INSERT` is also what makes "all matched rows or none" (implementation note 3) hold
 * for a genuine failure (a constraint violation this statement doesn't already tolerate, a connection
 * drop, etc.) without any extra code — a single SQL statement is already atomic; the transaction
 * wrapper the caller opens exists so this insert can later be extended to write alongside other rows
 * in the same commit, not because this one statement needs it to be atomic on its own.
 */
import { Inject, Injectable } from '@nestjs/common';
import type { Sequelize, Transaction } from 'sequelize';
import { QueryTypes } from 'sequelize';
import type { ActivityLogRow, ActivitySourceTransport } from '@/database/models/activity-log.model';

/**
 * DI token for this module's own runtime Postgres connection (the least-privilege `rap_app`
 * role — `AGENT-PROTOCOL.md` R1 — never the migration role from
 * `src/database/migration-connection.ts`). Defined here, not in the module file, matching
 * `campaign-config-snapshot.repository.ts`'s own precedent: the repository is the natural owner
 * of "the connection its own table is queried through".
 */
export const ACTIVITY_MAPPING_SEQUELIZE = Symbol('ACTIVITY_MAPPING_SEQUELIZE');

/**
 * One row this call wants written to `activity_logs` — one per matched tracker component
 * (`05-PROCESSING-PIPELINE.md` §1, step 5). Field names/types mirror `01-DATABASE.md` §3's column
 * list exactly (task implementation note 6) — `id`/`activity_reached_date`/`status`/`created_at`/
 * `updated_at` are intentionally absent here: every one of them either has a DB-side `DEFAULT`
 * this insert relies on (`status` always starts `'pending'`) or is generated by Postgres itself
 * (`id`).
 */
export interface FanOutRowInput {
  correlationId: string;
  dedupKey: string;
  tenantId: number;
  customerIdEncrypted: string;
  customerIdHash: string;
  customerIdType: string;
  activityPerformedDate: Date;
  transactionType: string | null;
  activityCode: string | null;
  activityType: string;
  activityCategory: string;
  activityValue: string;
  activityValueUnit: string;
  channel: string;
  activityPerformedEnv: string;
  activityName: string;
  campaignCode: string;
  trackerCode: string;
  trackerComponentCode: string;
  merchantCode: string | null;
  sourceTransport: ActivitySourceTransport;
}

/** What `RETURNING` gives back for each row that actually landed (i.e. was not skipped by
 * `ON CONFLICT DO NOTHING`) — enough for the caller to report `matchedTrackerComponents`
 * (`03-GRPC-CONTRACT.md` §1) without a second round trip. */
export interface InsertedFanOutRow {
  id: string;
  dedupKey: string;
  campaignCode: string;
  trackerCode: string;
  trackerComponentCode: string;
}

/** Column order this repository writes, in `01-DATABASE.md` §3's own column order (minus the
 * DB-generated/defaulted columns listed in `FanOutRowInput`'s own header comment). Shared between
 * the `VALUES` placeholder builder and the replacement-object builder so the two can never drift
 * out of sync with each other. */
const INSERT_COLUMNS: { column: string; field: keyof FanOutRowInput }[] = [
  { column: 'correlation_id', field: 'correlationId' },
  { column: 'dedup_key', field: 'dedupKey' },
  { column: 'tenant_id', field: 'tenantId' },
  { column: 'customer_id_encrypted', field: 'customerIdEncrypted' },
  { column: 'customer_id_hash', field: 'customerIdHash' },
  { column: 'customer_id_type', field: 'customerIdType' },
  { column: 'activity_performed_date', field: 'activityPerformedDate' },
  { column: 'transaction_type', field: 'transactionType' },
  { column: 'activity_code', field: 'activityCode' },
  { column: 'activity_type', field: 'activityType' },
  { column: 'activity_category', field: 'activityCategory' },
  { column: 'activity_value', field: 'activityValue' },
  { column: 'activity_value_unit', field: 'activityValueUnit' },
  { column: 'channel', field: 'channel' },
  { column: 'activity_performed_env', field: 'activityPerformedEnv' },
  { column: 'activity_name', field: 'activityName' },
  { column: 'campaign_code', field: 'campaignCode' },
  { column: 'tracker_code', field: 'trackerCode' },
  { column: 'tracker_component_code', field: 'trackerComponentCode' },
  { column: 'merchant_code', field: 'merchantCode' },
  { column: 'source_transport', field: 'sourceTransport' },
];

function toRow(raw: ActivityLogRow): InsertedFanOutRow {
  return {
    id: raw.id,
    dedupKey: raw.dedup_key,
    campaignCode: raw.campaign_code,
    trackerCode: raw.tracker_code,
    trackerComponentCode: raw.tracker_component_code,
  };
}

@Injectable()
export class ActivityLogsRepository {
  constructor(@Inject(ACTIVITY_MAPPING_SEQUELIZE) private readonly sequelize: Sequelize) {}

  /**
   * Inserts every row in `rows` in one statement, inside `transaction` — `[]` in, `[]` out
   * (no-op), never a query for zero rows. Rows whose `(dedup_key, campaign_code, tracker_code,
   * tracker_component_code)` tuple already exists are silently skipped (`uc_activity_logs_fanout`)
   * and simply absent from the returned array; the caller derives `accepted` vs `duplicate` from
   * whether anything came back at all (`05-PROCESSING-PIPELINE.md` §2).
   */
  async insertFanOutRows(
    rows: FanOutRowInput[],
    transaction: Transaction,
  ): Promise<InsertedFanOutRow[]> {
    if (rows.length === 0) {
      return [];
    }

    const replacements: Record<string, unknown> = {};
    const valueTuples = rows.map((row, index) => {
      const placeholders = INSERT_COLUMNS.map(({ column, field }) => {
        const key = `${column}_${index}`;
        replacements[key] = row[field];
        return `:${key}`;
      });
      // `status` is always `'pending'` on insert (`01-DATABASE.md` §3) — every other status
      // transition belongs to Wave 3, never to this fan-out insert.
      return `(${placeholders.join(', ')}, 'pending')`;
    });

    const columnList = INSERT_COLUMNS.map(({ column }) => column).join(', ');

    const inserted = await this.sequelize.query<ActivityLogRow>(
      `INSERT INTO realtime_activity_processing.activity_logs
         (${columnList}, status)
       VALUES
         ${valueTuples.join(',\n         ')}
       ON CONFLICT (dedup_key, campaign_code, tracker_code, tracker_component_code) DO NOTHING
       RETURNING *`,
      {
        type: QueryTypes.SELECT,
        replacements,
        transaction,
      },
    );

    return inserted.map(toRow);
  }
}
